version: "3.7"
services:
  app:
    command: /bin/bash -c "yarn && yarn start"
    build: ./app
    container_name: app
    working_dir: /app
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
volumes:
  node_modules: